# Generated by Django 6.0 on 2026-02-21 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_category_is_academic_category_sla_hours'),
        ('tickets', '0005_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='current_department',
            field=models.ForeignKey(blank=True, help_text='The department currently responsible for reviewing this ticket.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tickets', to='organization.department'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
