# Generated by Django 6.0 on 2026-02-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_current_department_ticket_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
    ]
