# Generated by Django 6.0 on 2026-02-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_is_escalated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('RESOLVED', 'resolved'), ('ESCALATED', 'escalated'), ('TRANSFERRED', 'transferred')], default='OPEN', max_length=20),
        ),
    ]
