# Generated by Django 6.0 on 2026-02-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('RESOLVED', 'resolved'), ('ESCALATED', 'escalated'), ('TRANSFERRED', 'transferred')], default='RESOLVED', max_length=20),
        ),
    ]
