# Generated by Django 6.0 on 2026-03-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_resolution_status_alter_ticket_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('RESOLVED', 'resolved'), ('ESCALATED', 'escalated'), ('TRANSFERRED', 'transferred'), ('CLOSED', 'closed'), ('REOPENED', 'reopened'), ('IN_PROGRESS', 'in_progress')], default='RESOLVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('RESOLVED', 'resolved'), ('ESCALATED', 'escalated'), ('TRANSFERRED', 'transferred'), ('CLOSED', 'closed'), ('REOPENED', 'reopened'), ('IN_PROGRESS', 'in_progress')], default='OPEN', max_length=20),
        ),
    ]
