# Generated by Django 6.0 on 2026-03-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_additionalinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pending_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
