# Generated by Django 6.0 on 2026-04-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_pending_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('RESOLVED', 'resolved'), ('ESCALATED', 'escalated'), ('TRANSFERRED', 'transferred'), ('CLOSED', 'closed'), ('REOPENED', 'reopened'), ('IN_PROGRESS', 'in progress'), ('REJECTED', 'rejected')], default='RESOLVED', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'open'), ('PENDING', 'pending'), ('RESOLVED', 'resolved'), ('ESCALATED', 'escalated'), ('TRANSFERRED', 'transferred'), ('CLOSED', 'closed'), ('REOPENED', 'reopened'), ('IN_PROGRESS', 'in progress'), ('REJECTED', 'rejected')], default='OPEN', max_length=20),
        ),
    ]
