# Generated by Django 6.0 on 2026-04-04 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_alter_resolution_status_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_deadline_warning_sent',
            field=models.BooleanField(default=False),
        ),
    ]
