# Generated by Django 6.0 on 2026-01-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organization', '0002_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='program',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='staff_role',
            field=models.CharField(choices=[('SENIOR', 'Senior'), ('STAFF', 'Staff')], default='STAFF', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='organization.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Staff', 'Staff'), ('Admin', 'Admin')], default='Student', max_length=20),
        ),
    ]
