# Generated by Django 6.0 on 2026-02-21 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_academic',
            field=models.BooleanField(default=False, help_text="If True, issues in this category are routed to the student's home department first."),
        ),
        migrations.AddField(
            model_name='category',
            name='sla_hours',
            field=models.PositiveIntegerField(default=48, help_text='Expected timeframe (in hours) to resolve issues in this category.'),
        ),
    ]
