# Generated by Django 6.0 on 2026-02-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_category_is_academic_category_sla_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sla_hours',
            new_name='resolution_timeframe',
        ),
    ]
